# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R_crzeuNhiArFxpeZf2mo5RvbtXIv5_b
"""

# Importing the libraries
import numpy as np
import pandas as pd
import pickle
import os
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import statsmodels.api as sm
from sklearn import linear_model
le = preprocessing.LabelEncoder()

dataset = pd.read_csv('Mobilbekas.csv')

dataset.head()

le.fit(dataset["Tahun"])
dataset["Tahun"] = le.transform(dataset["Tahun"])

le.fit(dataset["KM"])
dataset["KM"] = le.transform(dataset["KM"])

y = dataset["Harga"]

X = dataset[["Tahun", "KM",]]

#Splitting Training and Test Set
#Since we have a very small dataset, we will train our model with all availabe data.

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

#Fitting model with trainig data
regressor.fit(X, y)

# Saving model to disk
pickle.dump(regressor, open('model.pkl','wb'))

# Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))
print(model.predict([[10, 20]]))